keys:
  - &user_arunim age1dq28lv23cq4xenvfq5h2uqmp84kmhzxz9vauetdkwujk92evgqvsup4y4a
  - &laptop age1stu32rav09k9jtqg3kxm84amhecx5aadqzuja278wn0mqdhadvwqevxyr8

creation_rules:
  - path_regex: secrets.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_arunim
          - *laptop
